import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../src/component/Card";
import styles from "../styles/Home.module.css";
import { socialMediaSites } from "../data/socialMediaSites";
// import { BsFacebook } from "react-icons/bs";
import InputCard from "../src/component/InputCard";
import { useEffect, useState } from "react";
import { getFacebookUser, getGithubUser, getInstagramUser } from "../service";

const Home: NextPage = () => {
  const [username, setUsername] = useState("");
  const [isDataLoaded, setIsDataLoaded] = useState(false);
  const [socialSites, setSocialSites] = useState(socialMediaSites);

  let tempSites = socialMediaSites;

  const fetchUsername = async (username: string) => {
    console.log("Submitted", username);
    const githubData = await getGithubUser(username);
    // const instagramData = await getInstagramUser(username);
    // console.log("fetched Data  ", instagramData);
    tempSites[0] = {
      ...tempSites[0],
      ...{
        url: githubData.items.html_url,
        avatar_url: githubData.items.avatar_url,
        bio: githubData.items.bio,
        name: githubData.items.name,
      },
    };
    setSocialSites(tempSites);
    console.log("tempdata", tempSites);

    setIsDataLoaded(true);
  };

  useEffect(() => {
    (async () => {
      const instagramData = await getFacebookUser("alaspuresujay");
      console.log("fetched Data  ", instagramData);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Find your username</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <InputCard fetchUsername={fetchUsername} />

        {isDataLoaded && (
          <div className={styles.grid}>
            {socialSites.map((site) => (
              <Card
                key={site.label}
                // label={site.name}
                LogoImage={site.icon}
                // url={site.url}
                {...site}
              />
            ))}
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
